const mongoose = require("mongoose")

const studentSchema = mongoose.Schema({
    surname:{
        type:String,
    },
    first_name:{
        type:String,
    },
    other_name:{
        type:String,
    },
    email:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        lowercase:true
    },
    password:{
        type:String,
        required:true,
        min:5,
        trim:true
    },
    gender:{
        type:String,
    },
    add:{
        type:String,
    }, 
    matric:{
        type:String,
        unique:true,
        trim:true
    },
    verify:{
        type:Boolean,
        default:false
    },
    dob:{
        type:Date,
        trim:true
    },
    origin:{
        type:String,
    },
    height:{
        type:String,
    },
    mobile:{
        type:String,
        trim:true
    },
    profPic:{
        type:String,
        default:""
    },
    level:{
        type:String,
        trim:true
    },
    semester:{
        type:String,
        trim:true
    },
    faculty:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Faculty"
    },
    depart:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Department"
    },
    courseForm:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"CourseForm"
    }],
    program:{
        type:String,
    },
    hnd:{
        type:String,
        default:""
    },
    hnd_pic:{
        type:String,
        default:""
    },
    nd:{
        type:String,
        default:""
    },
    nd_pic:{
        type:String,
        default:""
    },
    ssce:{
        type:String,
        default:""
    },
    ssce_pic:{
        type:String,
        default:""
    },
    resetToken:String,
    expireToken:Date
},
{timestamps:true}
)


const StudentModel = mongoose.model("Students", studentSchema)

module.exports = StudentModel